### ISSUE TITLE
undefined in data will be stringfy  

### ISSUE THREAD

**Issue by winterJIE** [larryosborn/JSONP#14]
const data = {
 page: 1,
 size: undefined
},

jsonp({
  url: 'http://c.com',
 data: data,
 complete: function (data){
       console.log(data)
 }
});

I find in network tab in chrome the request url is http://c.com?page=1&size=undefined

the request url  should be http://c.com?page=1&size

please solve this issue as soon as possible, i used this jsonp module in my project

**Comment by larryosborn** [comment]
I don't agree with this bug. At the least it should be key/value pairs separated conjoined with an equal sign and separated with an ampersand. That's the W3C recommendation. That value is currently encoded with encodeURIComponent. I'm not sure why undefined would warrant special treatment over other data types like null, Boolean, etc.

You could omit the data attribute from the parameters and encode the url as you would like to customize.
